name: Manual QMK Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile Custom Firmware
        run: |
          make customkeyboard:vial
          
      - name: Upload Finished Firmware
        uses: actions/upload-artifact@v4
        with:
          name: compiled-firmware
          path: |
            *.uf2
            *.bin
            *.hex
            .build/*.uf2
