name: Manual Vial QMK Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Checkout Your Keyboard Custom Files
        uses: actions/checkout@v4
        with:
          path: custom_source

      - name: Checkout Official Vial-QMK Repository
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          ref: vial
          submodules: recursive
          path: qmk_firmware

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory /__w/qmk_firmware_customkeyboard/qmk_firmware_customkeyboard/qmk_firmware

      - name: Compile Custom Firmware
        run: |
          # Inject your keyboard files into the official Vial environment
          cp -r custom_source/keyboards/customkeyboard qmk_firmware/keyboards/
          
          cd qmk_firmware
          make customkeyboard:vial

      - name: Upload Finished Firmware
        uses: actions/upload-artifact@v4
        with:
          name: compiled-firmware
          path: |
            qmk_firmware/*.uf2
            qmk_firmware/.build/*.uf2
